spring:
  server:
    port: 8082
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Durga@10121997
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect